<?php
/**
 * Generated by Haxe 4.0.0 (git build development @ 3018ab1)
 */

namespace php;


/**
 * This class is used for accessing the local Web server and the current
 * client request and information.
 */
class Web {
	/**
	 * @var bool
	 */
	static public $isModNeko;




	/**
	 * @internal
	 * @access private
	 */
	static public function __hx__init ()
	{
		static $called = false;
		if ($called) return;
		$called = true;

#/Users/ut/haxe/versions/4.0.0-preview.3/std/php/Web.hx:420: characters 3-27
Web::$isModNeko = 0 !== strncasecmp(PHP_SAPI, "cli", 3);

	}
}


Boot::registerClass(Web::class, 'php.Web');
Web::__hx__init();
