<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 */

namespace haxe\rtti;

use \php\_Boot\HxAnon;
use \php\Boot;

/**
 * An API to access classes and enums metadata at runtime.
 * @see <https://haxe.org/manual/cr-rtti.html>
 */
class Meta {
	/**
	 * Returns the metadata that were declared for the given class fields or enum constructors
	 * 
	 * @param mixed $t
	 * 
	 * @return mixed
	 */
	static public function getFields ($t) {
		#/Users/ut/haxe/versions/4.0.0-rc.1/std/haxe/rtti/Meta.hx:94: characters 3-25
		$meta = Meta::getMeta($t);
		#/Users/ut/haxe/versions/4.0.0-rc.1/std/haxe/rtti/Meta.hx:95: characters 10-66
		if (($meta === null) || ($meta->fields === null)) {
			#/Users/ut/haxe/versions/4.0.0-rc.1/std/haxe/rtti/Meta.hx:95: characters 50-52
			return new HxAnon();
		} else {
			#/Users/ut/haxe/versions/4.0.0-rc.1/std/haxe/rtti/Meta.hx:95: characters 55-66
			return $meta->fields;
		}
	}

	/**
	 * @param mixed $t
	 * 
	 * @return object
	 */
	static public function getMeta ($t) {
		#/Users/ut/haxe/versions/4.0.0-rc.1/std/haxe/rtti/Meta.hx:60: characters 4-43
		return Boot::getMeta(Boot::dynamicField($t, 'phpClassName'));
	}
}

Boot::registerClass(Meta::class, 'haxe.rtti.Meta');
