<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 */

namespace haxe\io\_BytesData;

use \php\Boot;

class Container {
	/**
	 * @var mixed
	 */
	public $s;

	/**
	 * @param mixed $s
	 * 
	 * @return void
	 */
	public function __construct ($s) {
		#/Users/ut/haxe/versions/4.0.0-rc.1/std/php/_std/haxe/io/BytesData.hx:32: characters 45-55
		$this->s = $s;
	}
}

Boot::registerClass(Container::class, 'haxe.io._BytesData.Container');
