<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 */

use \php\Boot;
use \haxe\io\Output;
use \sys\io\FileOutput;

/**
 * This class gives you access to many base functionalities of system platforms. Looks in `sys` sub packages for more system APIs.
 */
class Sys {
	/**
	 * Gives the most precise timestamp value (in seconds) but only account for the actual time spent running on the CPU for the current thread/process.
	 * 
	 * @return float
	 */
	static public function cpuTime () {
		#/Users/ut/haxe/versions/4.0.0-rc.1/std/php/_std/Sys.hx:108: characters 3-54
		return microtime(true) - $_SERVER["REQUEST_TIME"];
	}

	/**
	 * Returns the process standard output on which you can write.
	 * 
	 * @return Output
	 */
	static public function stdout () {
		#/Users/ut/haxe/versions/4.0.0-rc.1/std/php/_std/Sys.hx:136: characters 3-43
		return new FileOutput((defined("STDOUT") ? STDOUT : fopen("php://stdout", "w")));
	}
}

Boot::registerClass(Sys::class, 'Sys');
