<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 */

namespace utest\utils;

use \php\Boot;
use \utest\Async;

class AccessoriesUtils {
	/**
	 * @param object $accessories
	 * 
	 * @return \Closure
	 */
	static public function getSetup ($accessories) {
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/utils/AccessoriesUtils.hx:13: characters 10-75
		if ($accessories->setup === null) {
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/utils/AccessoriesUtils.hx:13: characters 38-55
			return Boot::getStaticClosure(Async::class, 'getResolved');
		} else {
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/utils/AccessoriesUtils.hx:13: characters 58-75
			return $accessories->setup;
		}
	}

	/**
	 * @param object $accessories
	 * 
	 * @return \Closure
	 */
	static public function getSetupClass ($accessories) {
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/utils/AccessoriesUtils.hx:9: characters 10-85
		if ($accessories->setupClass === null) {
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/utils/AccessoriesUtils.hx:9: characters 43-60
			return Boot::getStaticClosure(Async::class, 'getResolved');
		} else {
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/utils/AccessoriesUtils.hx:9: characters 63-85
			return $accessories->setupClass;
		}
	}

	/**
	 * @param object $accessories
	 * 
	 * @return \Closure
	 */
	static public function getTeardown ($accessories) {
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/utils/AccessoriesUtils.hx:17: characters 10-81
		if ($accessories->teardown === null) {
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/utils/AccessoriesUtils.hx:17: characters 41-58
			return Boot::getStaticClosure(Async::class, 'getResolved');
		} else {
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/utils/AccessoriesUtils.hx:17: characters 61-81
			return $accessories->teardown;
		}
	}

	/**
	 * @param object $accessories
	 * 
	 * @return \Closure
	 */
	static public function getTeardownClass ($accessories) {
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/utils/AccessoriesUtils.hx:21: characters 10-91
		if ($accessories->teardownClass === null) {
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/utils/AccessoriesUtils.hx:21: characters 46-63
			return Boot::getStaticClosure(Async::class, 'getResolved');
		} else {
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/utils/AccessoriesUtils.hx:21: characters 66-91
			return $accessories->teardownClass;
		}
	}
}

Boot::registerClass(AccessoriesUtils::class, 'utest.utils.AccessoriesUtils');
