<?php
/**
 * Generated by Haxe 4.0.0 (git build development @ 3018ab1)
 */

namespace utest;

use \php\Boot;

class AccessoryName {
	/**
	 * @var string
	 * This method is executed before each test.
	 */
	const SETUP_CLASS_NAME = "setupClass";
	/**
	 * @var string
	 * This method is executed once before running the first test in the current class
	 */
	const SETUP_NAME = "setup";
	/**
	 * @var string
	 * This method is executed once after the last test in the current class is finished.
	 */
	const TEARDOWN_CLASS_NAME = "teardownClass";
	/**
	 * @var string
	 * This method is executed after each test.
	 */
	const TEARDOWN_NAME = "teardown";


}


Boot::registerClass(AccessoryName::class, 'utest.AccessoryName');
