<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 */

namespace utest;

use \php\Boot;
use \haxe\CallStack;
use \utest\_Dispatcher\EventException;
use \php\_Boot\HxException;

class Dispatcher {
	/**
	 * @var \Array_hx
	 */
	public $handlers;

	/**
	 * @return void
	 */
	static public function stop () {
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/Dispatcher.hx:45: characters 5-10
		throw new HxException(EventException::StopPropagation());
	}

	/**
	 * @return void
	 */
	public function __construct () {
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/Dispatcher.hx:12: characters 5-27
		$this->handlers = new \Array_hx();
	}

	/**
	 * @param \Closure $h
	 * 
	 * @return \Closure
	 */
	public function add ($h) {
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/Dispatcher.hx:15: characters 5-21
		$_this = $this->handlers;
		$_this->arr[$_this->length] = $h;
		++$_this->length;

		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/Dispatcher.hx:16: characters 5-13
		return $h;
	}

	/**
	 * @return void
	 */
	public function clear () {
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/Dispatcher.hx:27: characters 5-27
		$this->handlers = new \Array_hx();
	}

	/**
	 * @param mixed $e
	 * 
	 * @return bool
	 */
	public function dispatch ($e) {
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/Dispatcher.hx:30: lines 30-38
		try {
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/Dispatcher.hx:32: characters 7-34
			$list = (clone $this->handlers);
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/Dispatcher.hx:33: lines 33-34
			$_g = 0;
			while ($_g < $list->length) {
				#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/Dispatcher.hx:34: characters 9-13
				($list->arr[$_g++] ?? null)($e);
			}

			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/Dispatcher.hx:35: characters 7-18
			return true;
		} catch (\Throwable $__hx__caught_e) {
			CallStack::saveExceptionTrace($__hx__caught_e);
			$__hx__real_e = ($__hx__caught_e instanceof HxException ? $__hx__caught_e->e : $__hx__caught_e);
			if ($__hx__real_e instanceof EventException) {
				$exc = $__hx__real_e;
				#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/Dispatcher.hx:37: characters 7-19
				return false;
			} else  throw $__hx__caught_e;
		}
	}

	/**
	 * @return bool
	 */
	public function has () {
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/Dispatcher.hx:42: characters 5-31
		return $this->handlers->length > 0;
	}

	/**
	 * @param \Closure $h
	 * 
	 * @return \Closure
	 */
	public function remove ($h) {
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/Dispatcher.hx:20: lines 20-22
		$_g = 0;
		$_g1 = $this->handlers->length;
		while ($_g < $_g1) {
			$i = $_g++;
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/Dispatcher.hx:21: lines 21-22
			if (\Reflect::compareMethods(($this->handlers->arr[$i] ?? null), $h)) {
				#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/Dispatcher.hx:22: characters 9-40
				return ($this->handlers->splice($i, 1)->arr[0] ?? null);
			}
		}

		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/Dispatcher.hx:23: characters 5-16
		return null;
	}
}

Boot::registerClass(Dispatcher::class, 'utest.Dispatcher');
