<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 */

namespace _Array;

use \php\Boot;
use \php\_Boot\HxClosure;

class ArrayIterator {
	/**
	 * @var \Array_hx
	 */
	public $arr;
	/**
	 * @var int
	 */
	public $idx;

	/**
	 * @param \Array_hx $arr
	 * 
	 * @return void
	 */
	public function __construct ($arr) {
		#/Users/ut/haxe/versions/4.0.0-rc.1/std/php/_std/Array.hx:233: characters 3-17
		$this->arr = $arr;
		#/Users/ut/haxe/versions/4.0.0-rc.1/std/php/_std/Array.hx:234: characters 3-10
		$this->idx = 0;
	}

	/**
	 * @param string $method
	 * 
	 * @return HxClosure
	 */
	public function __get ($method) {
		#/Users/ut/haxe/versions/4.0.0-rc.1/std/php/_std/Array.hx:248: lines 248-251
		if ($method === "hasNext" || $method === "next") {
			#/Users/ut/haxe/versions/4.0.0-rc.1/std/php/_std/Array.hx:249: characters 28-54
			$target = $this;
			if (is_string($target)) {
				return Boot::getStaticClosure($target, $method);
			} else {
				return Boot::getInstanceClosure($target, $method);
			}
		} else {
			#/Users/ut/haxe/versions/4.0.0-rc.1/std/php/_std/Array.hx:250: characters 12-16
			return null;
		}
	}

	/**
	 * @return bool
	 */
	public function hasNext () {
		#/Users/ut/haxe/versions/4.0.0-rc.1/std/php/_std/Array.hx:238: characters 3-26
		return $this->idx < $this->arr->length;
	}

	/**
	 * @return mixed
	 */
	public function next () {
		#/Users/ut/haxe/versions/4.0.0-rc.1/std/php/_std/Array.hx:242: characters 3-20
		return ($this->arr->arr[$this->idx++] ?? null);
	}
}

Boot::registerClass(ArrayIterator::class, '_Array.ArrayIterator');
