<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 */

namespace utest\ui\common;

use \php\Boot;
use \utest\TestResult;
use \php\_Boot\HxString;
use \haxe\ds\StringMap;
use \php\_NativeIndexedArray\NativeIndexedArrayIterator;

class PackageResult {
	/**
	 * @var StringMap
	 */
	public $classes;
	/**
	 * @var bool
	 */
	public $isEmpty;
	/**
	 * @var string
	 */
	public $packageName;
	/**
	 * @var StringMap
	 */
	public $packages;
	/**
	 * @var ResultStats
	 */
	public $stats;

	/**
	 * @param string $packageName
	 * 
	 * @return void
	 */
	public function __construct ($packageName) {
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:8: characters 43-47
		$this->isEmpty = true;
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:15: characters 5-35
		$this->packageName = $packageName;
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:16: characters 5-24
		$this->classes = new StringMap();
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:17: characters 5-25
		$this->packages = new StringMap();
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:18: characters 5-30
		$this->stats = new ResultStats();
	}

	/**
	 * @param ClassResult $result
	 * 
	 * @return void
	 */
	public function addClass ($result) {
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:30: characters 5-20
		$this->isEmpty = false;
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:31: characters 5-42
		$this->classes->data[$result->className] = $result;
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:32: characters 5-29
		$this->stats->wire($result->stats);
	}

	/**
	 * @param PackageResult $result
	 * 
	 * @return void
	 */
	public function addPackage ($result) {
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:36: characters 5-20
		$this->isEmpty = false;
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:37: characters 5-45
		$this->packages->data[$result->packageName] = $result;
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:38: characters 5-29
		$this->stats->wire($result->stats);
	}

	/**
	 * @param TestResult $result
	 * @param bool $flattenPackage
	 * 
	 * @return void
	 */
	public function addResult ($result, $flattenPackage) {
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:22: characters 5-20
		$this->isEmpty = false;
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:26: characters 5-17
		$this->getOrCreateClass($this->getOrCreatePackage($result->pack, $flattenPackage, $this), $result->cls, $result->setup, $result->teardown)->add($this->createFixture($result->method, $result->assertations));
	}

	/**
	 * @param bool $errorsHavePriority
	 * 
	 * @return \Array_hx
	 */
	public function classNames ($errorsHavePriority = true) {
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:58: lines 58-89
		if ($errorsHavePriority === null) {
			$errorsHavePriority = true;
		}
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:59: characters 5-20
		$names = new \Array_hx();
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:60: characters 17-31
		$name = new NativeIndexedArrayIterator(array_map("strval", array_keys($this->classes->data)));
		while ($name->hasNext()) {
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:60: lines 60-61
			$name1 = $name->next();
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:61: characters 7-23
			$names->arr[$names->length] = $name1;
			++$names->length;
		}

		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:62: lines 62-87
		if ($errorsHavePriority) {
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:63: characters 7-21
			$me = $this;
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:64: lines 64-82
			usort($names->arr, function ($a, $b)  use (&$me) {
				#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:65: characters 9-39
				$as = $me->getClass($a)->stats;
				#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:66: characters 9-39
				$bs = $me->getClass($b)->stats;
				#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:67: lines 67-81
				if ($as->hasErrors) {
					#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:68: characters 18-129
					if (!$bs->hasErrors) {
						#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:68: characters 36-38
						return -1;
					} else if ($as->errors === $bs->errors) {
						#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:68: characters 67-88
						return \Reflect::compare($a, $b);
					} else {
						#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:68: characters 91-128
						return \Reflect::compare($as->errors, $bs->errors);
					}
				} else if ($bs->hasErrors) {
					#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:70: characters 11-19
					return 1;
				} else if ($as->hasFailures) {
					#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:72: characters 18-139
					if (!$bs->hasFailures) {
						#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:72: characters 38-40
						return -1;
					} else if ($as->failures === $bs->failures) {
						#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:72: characters 73-94
						return \Reflect::compare($a, $b);
					} else {
						#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:72: characters 97-138
						return \Reflect::compare($as->failures, $bs->failures);
					}
				} else if ($bs->hasFailures) {
					#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:74: characters 11-19
					return 1;
				} else if ($as->hasWarnings) {
					#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:76: characters 18-139
					if (!$bs->hasWarnings) {
						#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:76: characters 38-40
						return -1;
					} else if ($as->warnings === $bs->warnings) {
						#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:76: characters 73-94
						return \Reflect::compare($a, $b);
					} else {
						#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:76: characters 97-138
						return \Reflect::compare($as->warnings, $bs->warnings);
					}
				} else if ($bs->hasWarnings) {
					#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:78: characters 11-19
					return 1;
				} else {
					#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:80: characters 11-39
					return \Reflect::compare($a, $b);
				}
			});
		} else {
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:84: lines 84-86
			usort($names->arr, function ($a1, $b1) {
				#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:85: characters 9-37
				return \Reflect::compare($a1, $b1);
			});
		}
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:88: characters 5-17
		return $names;
	}

	/**
	 * @param string $method
	 * @param object $assertations
	 * 
	 * @return FixtureResult
	 */
	public function createFixture ($method, $assertations) {
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:126: characters 5-39
		$f = new FixtureResult($method);
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:127: characters 24-36
		$assertation = $assertations->iterator();
		while ($assertation->hasNext()) {
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:128: characters 7-25
			$f->add($assertation->next());
		}

		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:129: characters 5-13
		return $f;
	}

	/**
	 * @param string $name
	 * 
	 * @return bool
	 */
	public function existsClass ($name) {
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:46: characters 12-32
		return array_key_exists($name, $this->classes->data);
	}

	/**
	 * @param string $name
	 * 
	 * @return bool
	 */
	public function existsPackage ($name) {
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:42: characters 12-33
		return array_key_exists($name, $this->packages->data);
	}

	/**
	 * @param string $name
	 * 
	 * @return ClassResult
	 */
	public function getClass ($name) {
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:55: characters 12-29
		return ($this->classes->data[$name] ?? null);
	}

	/**
	 * @param PackageResult $pack
	 * @param string $cls
	 * @param string $setup
	 * @param string $teardown
	 * 
	 * @return ClassResult
	 */
	public function getOrCreateClass ($pack, $cls, $setup, $teardown) {
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:133: characters 5-56
		if ($pack->existsClass($cls)) {
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:133: characters 31-56
			return $pack->getClass($cls);
		}
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:134: characters 5-51
		$c = new ClassResult($cls, $setup, $teardown);
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:135: characters 5-21
		$pack->addClass($c);
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:136: characters 5-13
		return $c;
	}

	/**
	 * @param string $pack
	 * @param bool $flat
	 * @param PackageResult $ref
	 * 
	 * @return PackageResult
	 */
	public function getOrCreatePackage ($pack, $flat, $ref) {
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:140: characters 5-46
		if (($pack === null) || ($pack === "")) {
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:140: characters 36-46
			return $ref;
		}
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:141: lines 141-153
		if ($flat) {
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:142: lines 142-143
			if ($ref->existsPackage($pack)) {
				#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:143: characters 9-36
				return $ref->getPackage($pack);
			}
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:144: characters 7-39
			$p = new PackageResult($pack);
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:145: characters 7-24
			$ref->addPackage($p);
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:146: characters 7-15
			return $p;
		} else {
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:148: characters 7-35
			$parts = HxString::split($pack, ".");
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:149: lines 149-151
			$_g = 0;
			while ($_g < $parts->length) {
				#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:150: characters 9-50
				$ref = $this->getOrCreatePackage(($parts->arr[$_g++] ?? null), true, $ref);
			}

			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:152: characters 7-17
			return $ref;
		}
	}

	/**
	 * @param string $name
	 * 
	 * @return PackageResult
	 */
	public function getPackage ($name) {
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:50: characters 5-55
		if (($this->packageName === null) && ($name === "")) {
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:50: characters 44-55
			return $this;
		}
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:51: characters 12-30
		return ($this->packages->data[$name] ?? null);
	}

	/**
	 * @param bool $errorsHavePriority
	 * 
	 * @return \Array_hx
	 */
	public function packageNames ($errorsHavePriority = true) {
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:91: lines 91-123
		if ($errorsHavePriority === null) {
			$errorsHavePriority = true;
		}
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:92: characters 5-20
		$names = new \Array_hx();
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:93: characters 5-44
		if ($this->packageName === null) {
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:93: characters 30-44
			$names->arr[$names->length] = "";
			++$names->length;
		}
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:94: characters 17-32
		$name = new NativeIndexedArrayIterator(array_map("strval", array_keys($this->packages->data)));
		while ($name->hasNext()) {
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:94: lines 94-95
			$name1 = $name->next();
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:95: characters 7-23
			$names->arr[$names->length] = $name1;
			++$names->length;
		}

		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:96: lines 96-121
		if ($errorsHavePriority) {
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:97: characters 7-21
			$me = $this;
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:98: lines 98-116
			usort($names->arr, function ($a, $b)  use (&$me) {
				#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:99: characters 9-41
				$as = $me->getPackage($a)->stats;
				#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:100: characters 9-41
				$bs = $me->getPackage($b)->stats;
				#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:101: lines 101-115
				if ($as->hasErrors) {
					#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:102: characters 18-129
					if (!$bs->hasErrors) {
						#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:102: characters 36-38
						return -1;
					} else if ($as->errors === $bs->errors) {
						#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:102: characters 67-88
						return \Reflect::compare($a, $b);
					} else {
						#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:102: characters 91-128
						return \Reflect::compare($as->errors, $bs->errors);
					}
				} else if ($bs->hasErrors) {
					#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:104: characters 11-19
					return 1;
				} else if ($as->hasFailures) {
					#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:106: characters 18-139
					if (!$bs->hasFailures) {
						#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:106: characters 38-40
						return -1;
					} else if ($as->failures === $bs->failures) {
						#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:106: characters 73-94
						return \Reflect::compare($a, $b);
					} else {
						#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:106: characters 97-138
						return \Reflect::compare($as->failures, $bs->failures);
					}
				} else if ($bs->hasFailures) {
					#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:108: characters 11-19
					return 1;
				} else if ($as->hasWarnings) {
					#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:110: characters 18-139
					if (!$bs->hasWarnings) {
						#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:110: characters 38-40
						return -1;
					} else if ($as->warnings === $bs->warnings) {
						#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:110: characters 73-94
						return \Reflect::compare($a, $b);
					} else {
						#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:110: characters 97-138
						return \Reflect::compare($as->warnings, $bs->warnings);
					}
				} else if ($bs->hasWarnings) {
					#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:112: characters 11-19
					return 1;
				} else {
					#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:114: characters 11-39
					return \Reflect::compare($a, $b);
				}
			});
		} else {
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:118: lines 118-120
			usort($names->arr, function ($a1, $b1) {
				#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:119: characters 9-37
				return \Reflect::compare($a1, $b1);
			});
		}
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/031e6d47bf35ae55654eef5bd4dac8c07986ecfa/src/utest/ui/common/PackageResult.hx:122: characters 5-17
		return $names;
	}
}

Boot::registerClass(PackageResult::class, 'utest.ui.common.PackageResult');
