<?php
/**
 * Generated by Haxe 4.0.0 (git build development @ 3018ab1)
 */

namespace utest\ui\common;

use \php\_Boot\HxClosure;
use \utest\Notifier;
use \php\Boot;
use \php\_Boot\HxException;
use \utest\Runner;
use \haxe\Log;
use \utest\Assertation;
use \utest\Dispatcher;
use \haxe\ds\List_hx;
use \php\_Boot\HxAnon;
use \utest\TestResult;

class ResultAggregator {
	/**
	 * @var bool
	 */
	public $flattenPackage;
	/**
	 * @var Dispatcher
	 */
	public $onComplete;
	/**
	 * @var Dispatcher
	 */
	public $onProgress;
	/**
	 * @var Notifier
	 */
	public $onStart;
	/**
	 * @var PackageResult
	 */
	public $root;
	/**
	 * @var Runner
	 */
	public $runner;


	/**
	 * @param Runner $runner
	 * @param bool $flattenPackage
	 * 
	 * @return void
	 */
	public function __construct ($runner, $flattenPackage = false) {
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:16: lines 16-27
		if ($flattenPackage === null) {
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:16: lines 16-27
			$flattenPackage = false;
		}
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:17: characters 5-29
		if ($runner === null) {
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:17: characters 24-29
			throw new HxException("runner argument is null");
		}
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:18: characters 5-41
		$this->flattenPackage = $flattenPackage;
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:19: characters 5-25
		$this->runner = $runner;
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:20: characters 5-30
		$runner->onStart->add(new HxClosure($this, 'start'));
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:21: characters 5-36
		$runner->onProgress->add(new HxClosure($this, 'progress'));
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:22: characters 5-36
		$runner->onComplete->add(new HxClosure($this, 'complete'));
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:24: characters 5-29
		$this->onStart = new Notifier();
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:25: characters 5-34
		$this->onComplete = new Dispatcher();
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:26: characters 5-34
		$this->onProgress = new Dispatcher();
	}


	/**
	 * @return void
	 */
	public function checkNonITest () {
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:36: characters 5-22
		$first = null;
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:37: characters 5-19
		$total = 0;
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:38: lines 38-46
		$_g1 = 0;
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:38: lines 38-46
		$_g = $this->runner->length;
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:38: lines 38-46
		while ($_g1 < $_g) {
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:38: lines 38-46
			$_g1 = $_g1 + 1;
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:39: characters 7-42
			$fixture = $this->runner->getFixture($_g1 - 1);
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:40: lines 40-45
			if (!$fixture->isITest) {
				#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:41: characters 9-16
				$total = $total + 1;
				#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:42: lines 42-44
				if ($first === null) {
					#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:43: characters 11-67
					$first = \Type::getClassName(\Type::getClass($fixture->target));
				}
			}
		}

		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:47: lines 47-55
		if ($total > 0) {
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:49: lines 49-53
			$msg = null;
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:49: lines 49-53
			switch ($total) {
				case 1:
					#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:49: lines 49-53
					$msg = "" . ($first??'null') . " doesn't " . "implement utest.ITest. Non-ITest tests are deprecated. Implement utest.ITest or extend utest.Test.";
					break;
				case 2:
					#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:49: lines 49-53
					$msg = "" . ($first??'null') . " and 1 other don't " . "implement utest.ITest. Non-ITest tests are deprecated. Implement utest.ITest or extend utest.Test.";
					break;
				default:
					#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:49: lines 49-53
					$msg = "" . ($first??'null') . " and " . ($total??'null') . " others don't " . "implement utest.ITest. Non-ITest tests are deprecated. Implement utest.ITest or extend utest.Test.";
					break;
			}
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:54: characters 7-12
			(Log::$trace)($msg, new HxAnon([
				"fileName" => "utest/ui/common/ResultAggregator.hx",
				"lineNumber" => 54,
				"className" => "utest.ui.common.ResultAggregator",
				"methodName" => "checkNonITest",
			]));
		}
	}


	/**
	 * @param Runner $runner
	 * 
	 * @return void
	 */
	public function complete ($runner) {
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:96: lines 96-98
		if ($this->root->isEmpty) {
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:97: characters 7-51
			$this->root->addResult($this->createNoTestsResult(), false);
		}
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:99: characters 5-30
		$this->onComplete->dispatch($this->root);
	}


	/**
	 * @param TestResult $result
	 * 
	 * @return FixtureResult
	 */
	public function createFixture ($result) {
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:84: characters 5-46
		$f = new FixtureResult($result->method);
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:85: characters 24-43
		$_g_head = $result->assertations->h;
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:85: lines 85-86
		while ($_g_head !== null) {
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:85: lines 85-86
			$val = $_g_head->item;
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:85: lines 85-86
			$_g_head = $_g_head->next;
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:86: characters 7-25
			$f->add($val);
		}

		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:87: characters 5-13
		return $f;
	}


	/**
	 * @return TestResult
	 */
	public function createNoTestsResult () {
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:103: characters 5-35
		$result = new TestResult();
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:104: characters 5-21
		$result->pack = "";
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:105: characters 5-20
		$result->cls = "";
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:106: characters 5-23
		$result->method = "";
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:107: characters 5-37
		$result->assertations = new List_hx();
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:109: characters 5-64
		$result->assertations->add(Assertation::Failure("No tests executed.", new HxAnon([
			"fileName" => "",
			"lineNumber" => 1,
			"className" => "utest.Runner",
			"methodName" => "run",
		])));
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:110: characters 5-18
		return $result;
	}


	/**
	 * @param PackageResult $pack
	 * @param string $cls
	 * @param string $setup
	 * @param string $teardown
	 * 
	 * @return ClassResult
	 */
	public function getOrCreateClass ($pack, $cls, $setup, $teardown) {
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:77: characters 5-56
		if ($pack->existsClass($cls)) {
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:77: characters 31-56
			return $pack->getClass($cls);
		}
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:78: characters 5-51
		$c = new ClassResult($cls, $setup, $teardown);
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:79: characters 5-21
		$pack->addClass($c);
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:80: characters 5-13
		return $c;
	}


	/**
	 * @param string $pack
	 * @param bool $flat
	 * @param PackageResult $ref
	 * 
	 * @return PackageResult
	 */
	public function getOrCreatePackage ($pack, $flat, $ref = null) {
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:59: characters 5-31
		if ($ref === null) {
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:59: characters 21-31
			$ref = $this->root;
		}
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:60: characters 5-46
		if (($pack === null) || ($pack === "")) {
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:60: characters 36-46
			return $ref;
		}
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:61: lines 61-73
		if ($flat) {
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:62: lines 62-63
			if ($ref->existsPackage($pack)) {
				#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:63: characters 9-36
				return $ref->getPackage($pack);
			}
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:64: characters 7-39
			$p = new PackageResult($pack);
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:65: characters 7-24
			$ref->addPackage($p);
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:66: characters 7-15
			return $p;
		} else {
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:68: characters 7-35
			$parts = \Array_hx::wrap(explode(".", $pack));
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:69: lines 69-71
			$_g = 0;
			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:69: lines 69-71
			while ($_g < $parts->length) {
				#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:69: characters 11-15
				$part = ($parts->arr[$_g] ?? null);
				#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:69: lines 69-71
				$_g = $_g + 1;
				#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:70: characters 9-50
				$ref = $this->getOrCreatePackage($part, true, $ref);
			}

			#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:72: characters 7-17
			return $ref;
		}
	}


	/**
	 * @param object $e
	 * 
	 * @return void
	 */
	public function progress ($e) {
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:91: characters 5-45
		$this->root->addResult($e->result, $this->flattenPackage);
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:92: characters 5-27
		$this->onProgress->dispatch($e);
	}


	/**
	 * @param Runner $runner
	 * 
	 * @return void
	 */
	public function start ($runner) {
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:30: characters 5-20
		$this->checkNonITest();
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:31: characters 5-35
		$this->root = new PackageResult(null);
		#/Users/ut/haxe/haxe_libraries/utest/1.9.5/github/aca590b256e0879cd7fbfcd47ca4f3a0a0ce1845/src/utest/ui/common/ResultAggregator.hx:32: characters 5-23
		$this->onStart->dispatch();
	}
}


Boot::registerClass(ResultAggregator::class, 'utest.ui.common.ResultAggregator');
