<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 */

namespace utest\ui\common;

use \php\Boot;
use \php\_Boot\HxEnum;

class SuccessResultsDisplayMode extends HxEnum {
	/**
	 * @return SuccessResultsDisplayMode
	 */
	static public function AlwaysShowSuccessResults () {
		static $inst = null;
		if (!$inst) $inst = new SuccessResultsDisplayMode('AlwaysShowSuccessResults', 0, []);
		return $inst;
	}

	/**
	 * @return SuccessResultsDisplayMode
	 */
	static public function NeverShowSuccessResults () {
		static $inst = null;
		if (!$inst) $inst = new SuccessResultsDisplayMode('NeverShowSuccessResults', 1, []);
		return $inst;
	}

	/**
	 * @return SuccessResultsDisplayMode
	 */
	static public function ShowSuccessResultsWithNoErrors () {
		static $inst = null;
		if (!$inst) $inst = new SuccessResultsDisplayMode('ShowSuccessResultsWithNoErrors', 2, []);
		return $inst;
	}

	/**
	 * Returns array of (constructorIndex => constructorName)
	 *
	 * @return string[]
	 */
	static public function __hx__list () {
		return [
			0 => 'AlwaysShowSuccessResults',
			1 => 'NeverShowSuccessResults',
			2 => 'ShowSuccessResultsWithNoErrors',
		];
	}

	/**
	 * Returns array of (constructorName => parametersCount)
	 *
	 * @return int[]
	 */
	static public function __hx__paramsCount () {
		return [
			'AlwaysShowSuccessResults' => 0,
			'NeverShowSuccessResults' => 0,
			'ShowSuccessResultsWithNoErrors' => 0,
		];
	}
}

Boot::registerClass(SuccessResultsDisplayMode::class, 'utest.ui.common.SuccessResultsDisplayMode');
